sudo: required

services:
  - docker                  

before_install:            
  - mkdir -p output
  - docker pull asciidoctor/docker-asciidoctor

script:
  - ./check_rule_ids.sh > check_rule_ids_result
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-html asciidoctor/docker-asciidoctor asciidoctor -D /documents/output index.adoc
  - cp -r models/* output/
  - cp -r -n legacy/* output/
  - ./generate_rules_json.sh output
  - mv output/index.pdf output/zalando-guidelines.pdf
  - mv output/index.epub output/zalando-guidelines.epub

after_error:
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf
  - docker logs asciidoc-to-epub3
  - cat check_rule_ids_result

after_failure:
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf
  - docker logs asciidoc-to-epub3
  - cat check_rule_ids_result

after_success: ./travis_deploy.sh
